export const GET_MUSIC_LOADDING="GET_MUSIC_LOADDING"
export const GET_MUSIC_SUCCESS="GET_MUSIC_SUCCESS"
export const GET_MUSIC_ERROR="GET_MUSIC_ERROR"


export const EDIT_MUSIC_LOADDING="EDIT_MUSIC_LOADDING"
export const EDIT_MUSIC_SUCCESS= "EDIT_MUSIC_SUCCESS"
export const EDIT_MUSIC_ERROR=   "EDIT_MUSIC_ERROR"